language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_deploy:
- sudo chown -R $(whoami) /usr/local/bin/
- curl -SL https://github.com/apex/up/releases/download/v0.5.11/up_0.5.11_linux_amd64.tar.gz | tar xz -C /usr/local/bin up
- up upgrade > /dev/null
deploy:
- provider: script
  script: up deploy staging
  skip_cleanup: true
  on:
    branch: master
    tags: false
- provider: script
  script: up deploy production
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
  - AWS_REGION: us-west-2
  - secure: YxEn6ca4eLzGNA9qcPhIePlGDE3hcjqIV5JSzltpzyzhVr3LKYk2KmSdWksFFbbcuBZOVA7kuP+yPW+yTkWvxPhsP9gfZEvJQ2CIcSVgmWiTXvKEYZXQ8fV5MtrY4ALSeSZ+C3SS4YvF/9xVV51xQftavLMb4dF6saTmp4dnzidMw30ncyGG69RGTsW4/itFfhGtLtng+QueqJ1Vyqno6sQGp7f6YjE2eKYcxS9WMdbJRPtZ1ki9/dzor6WSc580/4dC6kZfpvqxihu6pl5V9ZI+vUshr/nDv2KKJyBaEfLQOWTaw7bHH6IzVdkhVP7c+uwQWo/4v+52fKdX750mmSSZeDTij7O9mSTid6ddqUXU09w1gzwuDU2RwNusQX3vIvG0ofMhyoiOLinhKHqF7uagSjAuf+O3MnRnPzaS0IO4iKmI90L1EzccTOZGVjXCF2MqoBRJGze0QOxeULmOlZzsuqFwushVGO2kdgYmYXWh0k562eCrIvGUE908wnr9OoQ+957/NbIMAOfLd7keVRtvAAqlYmr6TFFwCZ4DYG+CN7T83e32AhNU4uZw1S8rctVXYiHCBgi5Qx8ouhFgA3ZS3rLP8u7X2/IgQkfqZaTw7qEg2i2qFXUU8YFgu956uIMXsNrPHUV9RtXsvESA60j4nj78QMIAwE7DKa2o5wE=
  - secure: RZoyIBjLqGCVWpBSwHeNquDvtfqKceDiKraGD129oV5pgZ4cfNZJ+63j0mBnQ1hofaI1VEGtZ50cc2elknnrKAOllGE/jmBqD67VeWuLvPoSZIunUzAf8hvUICQ7o7yuCSrrHocl79Wl7h07QXV8hrv0y3gHbN9vm7GVOD6YdkFIfeMoqjL7LymHeQsisSGRqMvvR1qBZTgiVLihgPN25qj3drvuD6NXlrMyRq78WIVxtm9CIULdmgnAdbhFWjtotrAUudg/mFV0LITmC3jO88WN6CSDVqF/TWJmYrWKITcCjTTFYLgv74tCKXUFohSY3mUCRwfO93z/1eHcRz64t8iunsKrRtYTTuWIGrgjMJXqwiPLws4Ldjw5Dwf4mzobCAsk86UufJZZJDQeOoTJvrVIg0bmhGD1ha3CyGgosmf3JYhbJM9hapySSG9mhE33hJBvtA83jgigffNtI6+oU8lDDw+EloD8tP0QySQv3uL6YEiPnMTFPBTePF/zT42fpfFCIA3thV8VTB4o3XSWShSmSfjh2matmo3n/NtnrqALYz1u5ml9Y5v9BZ4j/T8FlOjZBToKAdXfSFMTAGC/9yHMZX4m9hHSH8ZnTheOeU6oOGQISspHWqyMDtVKliDP8DqJFW4OzOe4Fy0jJIW2qVPRQxyQxBXlwWDXGQsmlWg=
  - secure: GCsgbblVPv5CKlRfKfBpdIEqu/D10gdSdkob2s8XXJ0GZDZDbLsr6VVPXxKn+Ff1DhBxt5LHBakLEoYBDcm+0bVbBSeKuO3vej2pGsBCdb1eRZeX92La5khmF4SLbUiNvDZLlzsb6XjgOaw9q7C1dNPHbw9FYiCv+Bao0Y7f/7kQWH2rKcjNg6TZP6F4UArUrwPpKOG8sKY/lGqGy9VkF6HQjfylfg3YcFGS6xxAcsqLGxslwLVW0XU8hNNkK7/U51eODsMph+1ndgFHh9lC2Oy8iyegK4Ergol9Wxy7PkSnFvANZ6Han09r3vssjomUY1FCxqI+qy5sYCTq+vk77qKqpG7q96+Dm46oTUKYLBMQD0TOjkKdPczZTIzZGzAJc88q4a3ydqyBO27Wthhev0WXqJJ2dSJoz0Xp4bP6L8IZOaRM+9ZVL2ldR3x5Rno/kIlYGBmLlw6I7YlHgAsLmVDDWYPsPHmsImO4kwugxU7XCXVmyxfP6CmOEkSgt/rQatQ6x/5hKSwuUs8JfFQQ2Mo8SaFnZx9e3YxIw+tlaGaf8xgIbkMRTj5B/7kSwg7C4sp3QrjefAPxFpLpPU6A58wXUtvZmCyEvzp/kePBl6b0mZwpldvqu7DRY/7jtQCI+/JW2BZKRQFgotiA5up/TIfYEfwXerc7eMLSs82XB+w=
